### ISSUE TITLE
RTL overlapping ripple with label text

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-radio-button#108]
This is currently a bug in Chromium on the new md-settings page. For detailed info & repro, see:  https://bugs.chromium.org/p/chromium/issues/detail?id=674826

### Description

In an RTL context, the ripple can overlap with the label text.

### Expected outcome

Same as LTR - there is adequate spacing between label and ripple.

### Actual outcome

There isn't any space between the button and the label text.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by t-soares** [comment]
The new md-settings page is not setting the HTML dir attribute. It is only setting the CSS direction property to RTL.
The radio-button is using the following CSS selector to identify the page directionality:
:host-context([dir="rtl"])
It relies on the HTML dir attribute to identify the page directionality. Others md-settings pages also sets the dir attribute. So, I think it is a matter of setting the dir attribute on the pages that are not doing that.

**Comment by tjsavage** [comment]
Ah yes! Good catch! Thank you. Closing here for now.
