### ISSUE TITLE
Add a mixin for internal radio label.

### ISSUE THREAD

**Issue by sammiequon71** [PolymerElements/paper-radio-button#118]
Add a mixin to style the internal radio label. This is helpful if we have children elements which want to be styled in a certain way. Right now they are limited by #radioLabel.

**Comment by danbeam** [comment]
if you were wondering how/where we'd like to use this new mixin, here's a concrete example:

https://codereview.chromium.org/2823713002/diff/100001/chrome/browser/resources/settings/people_page/lock_screen.html

**Comment by bicknellr** [comment]
Seems like a good idea and consistent with: PolymerElements/paper-checkbox#119.

**Comment by bicknellr** [comment]
Fixed in #119.
