### ISSUE TITLE
paper-radio-button accessibility report

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-radio-button#15]
For the most part, this is working great! The only issue that came up in the accessibility developer tools audit is that the contrast of the disabled radio buttons is too light. I know this is actually the intent though, so not sure any action is needed here.

**Comment by notwaldorf** [comment]
I've increased the contrast a little bit, but also decreased the contrast of the focus ripple. Before I merge this, would you mind double checking it looks ok? Thanks!

Before:
![screen shot 2015-05-19 at 10 59 32 am](https://cloud.githubusercontent.com/assets/1369170/7710108/7e3b6aae-fe16-11e4-8f6f-6b264ed9597f.png)

After:
![screen shot 2015-05-19 at 11 00 57 am](https://cloud.githubusercontent.com/assets/1369170/7710318/e48067aa-fe17-11e4-9e42-2bf4e80c7361.png)

**Comment by lpalmaro** [comment]
The new disabled radio button looks much better! Any chance we can make the
focus ripple slightly darker though (somewhere in between the old and new
shade)? It's much harder to see in the lighter color.

**Comment by notwaldorf** [comment]
How about (it's very slightly darker):
![screen shot 2015-05-19 at 11 11 55 am](https://cloud.githubusercontent.com/assets/1369170/7710323/e9b64a0a-fe17-11e4-8d95-e6eefde819ad.png)

**Comment by lpalmaro** [comment]
Better! Lastly, although the disabled radio button itself is much better
now, the text is super light. Can we try just a bit darker? I know that is
light because it's letting the user know it's disabled, but if some users
aren't able to read it at all, that can be frustrating. Thanks for your
flexibility here!

**Comment by notwaldorf** [comment]
Like this? 
![screen shot 2015-05-19 at 11 31 29 am](https://cloud.githubusercontent.com/assets/1369170/7710739/a6443414-fe1a-11e4-8747-62845346a589.png)

**Comment by lpalmaro** [comment]
Much better! Thank you!

**Comment by notwaldorf** [comment]
No worries! Thanks for all the help :)

**Comment by lpalmaro** [comment]
Totally my pleasure!

**Comment by notwaldorf** [comment]
Fixed by https://github.com/PolymerElements/paper-radio-button/pull/20

**Comment by lpalmaro** [comment]
Awesome - thanks!
