### ISSUE TITLE
material design spec audit - few changes needed

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-radio-button#16]
- Ripple should always be centered, regardless of where click or tap starts. That way it doesn't get clipped.
- Opacity on ripple _might_ be a little high: http://www.google.com/design/spec/components/selection-controls.html#

**Comment by notwaldorf** [comment]
Partly fixed in https://github.com/PolymerElements/paper-radio-button/pull/20

**Comment by blasten** [comment]
All good now
