### ISSUE TITLE
Radio button can be unchecked after first being checked

### ISSUE THREAD

**Issue by Awarua-** [PolymerElements/paper-radio-button#27]
This seems counter intuitive to the first few lines in the readme.

" paper-radio-button is a button that can be either checked or unchecked. User can tap the radio button to check it. But it cannot be unchecked by tapping once checked."

Notably when in a paper-radio-group, the selected property of the paper-radio-group remains if the paper-radio-button is checked then unchecked.

**Comment by notwaldorf** [comment]
Ah, the docs are out of date. Thanks for catching this, I'll take a look.
