### ISSUE TITLE
don't react to right-click

### ISSUE THREAD

**Issue by drewpca** [PolymerElements/paper-radio-button#33]
Right-click on a radio button: the ink expands, the browser's popup shows, and when you press escape key to close the popup, the ink remains on.

Expected: no reaction to right-click at all.

**Comment by drewpca** [comment]
![image](https://cloud.githubusercontent.com/assets/5224714/8192306/ff67e5e6-1421-11e5-9b6b-f0b2a57e3c12.png)

**Comment by notwaldorf** [comment]
@cdata I think this is the `pointerDown` code that incorrectly thinks this is a keyboard focus (possibly because you press `esc`)

**Comment by cdata** [comment]
Annoying! I'll take a look.

**Comment by anthonytordillos** [comment]
Any update here? Specifically with regards to PolymerElements/paper-button#24.

**Comment by cdata** [comment]
This issue should be resolved by polymerelements/iron-behaviors#23. Please re-open if there is still a problem!
