### ISSUE TITLE
Can't disable toggles.

### ISSUE THREAD

**Issue by coreyfarrell** [PolymerElements/paper-radio-button#39]
It is impossible to prevent users from unselecting a radio button by clicking on it.  When a default option is selected it should be possible to prevent having no radio button selected within that radio group.

I'm unsure the best way to fix.  We could add a property to Polymer.IronButtonStateImpl clickactivate.  Default it to false, but set to true for paper-radio-button.  Then have _tapHandler deal with radio buttons by checking this.clickactivate.  I can prepare a PR once if this is a reasonable approach.  I'm open to suggestions for better name of the property, or different ways to deal with this.

**Comment by notwaldorf** [comment]
Have you tried using a `<paper-radio-group>` (https://github.com/PolymerElements/paper-radio-group) ? That logic is baked into that element (because a group is aware of the radio button children it has, and controls whether or not a selection exists).

**Comment by coreyfarrell** [comment]
I reinstalled from bower and I'm no longer experiencing this issue.  I believe I must have been using a copy of paper-radio-group prior to merge PolymerElements/paper-radio-group#9.  Sorry for the noise, closing issue.
