### ISSUE TITLE
paper-radio-button and paper-checkbox hide content when empty

### ISSUE THREAD

**Issue by dschuyler** [PolymerElements/paper-radio-button#51]
Hi,

We have entries such as:
<paper-radio-button name="5" i18n-content="onStartupOpenNewTab">
</paper-radio-button>

The content is initially empty.  It's filled in later with a localized string.  It seems that the radio buttons and checkboxes will hide the label if it's initially empty.

I've ended up hacking around it with something like this, 'placeholder' can be any value:
<paper-radio-button name="5" i18n-content="onStartupOpenNewTab">placeholder
</paper-radio-button>

Could the hiding of the label be done through other means?  Maybe a property on the radio-button or checkbox element?

**Comment by notwaldorf** [comment]
Have you tried the latest version of the elements? It should have been fixed about 3 days ago :)
(you might have to do a `bower cache clean` to make sure you're picking up the latest)

**Comment by dschuyler** [comment]
Awesome thanks!  We're very likely lagging on the version.  I'll check that and follow up on this after I check it on the newer version.

**Comment by notwaldorf** [comment]
I'm going to close this, since it's pretty old (and I think fixed), but please re-open it if it didn't fix your problem! :)

**Comment by dschuyler** [comment]
Yes, thanks!  This is fixed.
