### ISSUE TITLE
Ripple doesn't go away when label is tapped

### ISSUE THREAD

**Issue by bendavis78** [PolymerElements/paper-radio-button#58]
In Chrome, when you tap the label of the button, the ripple does not go away. In some cases (such as with the [demo](https://elements.polymer-project.org/elements/paper-radio-button?view=demo:demo/index.html)), the ripple doesn't appear unless you switch browser tabs and back. In either case, the ripple sticks around and does not go away until a blur event.

**Comment by notwaldorf** [comment]
@bendavis78 I'm not sure I understand what you mean. How is the ripple initially being displayed? Is it because you tabbed to the checkbox to focus it? If that's so, clicking on the label hides the ripple for me. Just clicking on the label with no ripple displaying will not display the ripple.

**Comment by notwaldorf** [comment]
Closing, as there's no response. Please re-open with more details if this still occurs.

**Comment by sandeshdamkondwar** [comment]
@notwaldorf I was trying to find the same sort of issue because I'm facing same trouble here.

**Comment by sandeshdamkondwar** [comment]
@notwaldorf 
Hi Monica, inspect [this page](https://elements.polymer-project.org/elements/paper-radio-group?view=demo:demo/index.html&active=paper-radio-group) in chrome developer tools and select any mobile device.
You will see that ripple stays there after selecting the radio button.
