### ISSUE TITLE
paper-tabs is breaking focus state for paper-radio-button

### ISSUE THREAD

**Issue by nick211** [PolymerElements/paper-radio-button#68]
E.g.

```
<paper-tabs>
  <paper-tab name="one">One</paper-tab>
  <paper-tab name="two">Two</paper-tab>
</paper-tabs>

<paper-radio-group selected="small">
  <paper-radio-button name="small">Small</paper-radio-button>
  <paper-radio-button name="medium">Medium</paper-radio-button>
  <paper-radio-button name="large">Large</paper-radio-button>
</paper-radio-group>
```

When tabbing through the UI, no focus state is shown for the radio buttons (only a very short focus "flicker" is shown when the focus leaves a radio button).

Adding attribute "hidden" to the paper-tabs element fixes the issue, indicating that paper-tabs causes the issue (I haven't looked at the cause in more detail; perhaps the cause is more general).

Note that paper-tabs and the paper-radio-button don't need to be DOM siblings to trigger the broken behavior (in my app, the paper-tabs and paper-radio-button are in different parts of the DOM, yet the broken behavior is still happening).

**Comment by notwaldorf** [comment]
I've made a jsbin with your code (http://jsbin.com/puhepo/edit?html,output), and I can repro this on Firefox, but not Chrome or Safari.

Since you think this is a `paper-tabs` issue, I'm going to pass this on to @bicknellr to take a look at it :)

**Comment by bicknellr** [comment]
Looks like this might be the result of `iron-flex-layout` being temporarily broken recently. @nick211 update and try again?

**Comment by bicknellr** [comment]
@notwaldorf just pointed out to me that this is from Nov. 2nd. so the `iron-flex-layout` thing must not be related. But could you try to repro this again? It seems to have been fixed anyways.

**Comment by notwaldorf** [comment]
Closing this, as there hasn't been any activity on this lately. Please re-open if this is still occurring.
