### ISSUE TITLE
Dynamically create a paper-radio-button

### ISSUE THREAD

**Issue by IchordeDionysos** [PolymerElements/paper-radio-button#83]
I just can't create a paper-radio-button dynamically. 
I don't know why because I can create all of my own custom elements too.
Maybe I just have made a typo:

``` javascript
var tree = document.createElement('paper-radio-button');
tree.name = trees[i].name;
tree.innerHTML = trees[i].name;
treeContainer.appendChild(tree);
```

`trees` is just an array of binary-tree elements which are currently on the site and the name of them are some kind of ID

This is my code and it just results in: `<paper-radio-button>treeName</paper-radio-button>`
I have imported the element because below I have another radio group (created on load time) and it's displayed dynamically

**Comment by IchordeDionysos** [comment]
Ahh I know I can't set the innerHTML to the tree name ...
But how can I set the "description" of the radio button otherwise?

**Comment by notwaldorf** [comment]
You just need to use a text node: http://jsbin.com/hacofo/4/edit?html,output

```
      var btn = document.createElement('paper-radio-button');
      var text = document.createElement('text');
      text.textContent = 'maple';
      btn.appendChild(text);
      document.body.appendChild(btn);
```

**Comment by IchordeDionysos** [comment]
Thanks, I found that way by myself.
But when I want to select one of the dynamically created paper-radio-buttons, they disappear somehow ...
I have wrapped them into an `<paper-radio-group>` 
It is really confusing, maybe it's a bug or I've done something wrong
Maybe you want to have a look on it

But for now I did it with a `dom-repeat template`

**Comment by hadams95** [comment]
The bug @IchordeDionysos described with the radio buttons disappearing on click (also on right-click strangely) when they are dynamically generated with document.createElement is still an issue; one that I am currently facing now.  In fact it also occurs when the checked property of a button is set to true.

**Comment by hadams95** [comment]
If anyone at all is still facing this issue described above with dynamically creating the radio buttons and them disappearing on click, I found a fix that works for me.  Where I was performing `exampleGroup.appendChild(exampleButton)`, I changed that to `Polymer.dom(exampleGroup).appendChild(exampleButton)` and after that I no longer faced the issue, I hope the same works for anyone else
