### ISSUE TITLE
"pointer-events: none" prevents... pointer events

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/paper-radio-button#86]
`paper-radio-button`, and probably others (`paper-checkbox`), styles its label with `pointer-events: none` even when the element is enabled.

this prevents links from being clickable: https://jsfiddle.net/mgiuffrida/ye2u2mvm/

perhaps this is WAI, but it's frustratingly difficult to provide your own label to the element, because things don't align right without extra CSS, and clilcking the label doesn't trigger the button without JavaScript. perhaps a --paper-radio-button-label mixin would be useful?

**Comment by notwaldorf** [comment]
I think a better question is "why do they have pointer events none". Maybe they don't need to?

/cc @bicknellr

**Comment by bicknellr** [comment]
Same as PolymerElements/paper-checkbox#100.

**Comment by bicknellr** [comment]
Source of `pointer-events: none;`: @ca3c3c2. Probably safe to say it's not necessary anymore.
